[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/info.py"
name = "í•™ìƒì •ë³´"
icon = "ğŸ§‘ğŸ»â€ğŸ’»"

[[pages]]
path = "pages/statistic.py"
name = "í†µê³„í™•ì¸"
icon = "ğŸ”"

[[pages]]
path = "pages/manage.py"
name = "ì§„ë„ê´€ë¦¬"
icon = "ğŸ“Œ"

[[pages]]
path = "pages/hub.py"
name = "ì €ì¥ì†Œ"
icon = "ğŸ“‘"

[[pages]]
path = "pages/agent.py"
name = "Agent"
icon = "ğŸ¤–"